config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'invoices#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:amount, :comapany, :contragent, :currency, :data)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<div class="col-xs-12">
<%= simple_form_for(@invoice) do |f| %>
  <div id="invoice-wrap">
    <%= f.error_notification %>
    <div class="row">
      <div class="col-xs-12">
        <h3 class="page-header">INVOICE<small class="pull-right"></small></h3>
      </div><!-- /.col -->
    </div>

    <div class="row invoice-info">
      <div class="col-xs-4 invoice-col">
        From
        <address>
          <%= f.input_field :comapany, class: "form-control", id: "1" %>
          <input class="form-control" id= "2"  placeholder="address line 1" />
          <input class="form-control" id= "3"  placeholder="address line 2" />
          <input class="form-control" id= "4"  placeholder="phone number" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        To
        <address>
          <%= f.input_field :contragent, class: "form-control", id: "5" %>
          <input class="form-control" id= "6"  placeholder="address line 1" />
          <input class="form-control" id= "7"  placeholder="address line 2" />
          <input class="form-control" id= "8"  placeholder="phone number" />
        </address>
      </div><!-- /.col -->
      <div class="col-xs-4 invoice-col">
        <form class="form-horizontal">

          <div class="form-group">
            <div class="col-xs-4"><label>Invoice #</label></div>
            <div class="col-xs-8 invoice_num"></div>
          </div>
          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :date, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :data, class: "form-control datepicker", as: :string %></div>
          </div>

          <div class="col-xs-12"></div>
          <div class="form-group">
            <div class="col-xs-4"><%= f.label :currency, required: false %></div>
            <div class="col-xs-8"><%= f.input_field :currency,  class: "form-control" %></div>
          </div>

        <div class="col-xs-12"></div>
        <div class="form-group">
          <div class="col-xs-4"><%= f.label :amount, required: false %></div>
          <div class="col-xs-8"><%= f.input_field :amount, class: "form-control"  %>
        </div>
        </div>
        </form>
        </div>
      </div>

    <div class="row">
      <div class="col-xs-12 pull-left">
        
        <%= f.button :submit, 'Submit Payment', class: 'btn btn-warning btn-sm' %>    
      </div>
    </div>

  </div>
  <% end %>
</div>

app/views/invoices/edit.html.erb
<div class="row">
 <div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
   <div class="panel-heading">
   <h3 class="panel-title">Edit Invoice </h3>
    </div>
        <div class="panel-body"> 
        <%= render 'form' %>
        
      </div>
      <div class="panel-footer">
      <%= link_to 'Back', invoices_path,class: "btn btn-danger" %>
   <%= link_to 'Show', @invoice, class: "btn btn-success" %> |
   
    </div>
    </div>
    </div>
    </div>

app/views/invoices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
 <div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
   <div class="panel-heading">
    <h3 class="panel-title">Invoices</h3>
    </div>
        <div class="panel-body">   
          <table class="table table-hover table-bordered">
            <thead>
                <tr>
                  <th>Comapany</th>
                  <th>Contragent</th>
                  <th>Currency</th>
                  <th>Data</th>
                  <th colspan="3"></th>
                </tr>
            </thead>

          <tbody>
            <% @invoices.each do |invoice| %>
              <tr>
                
                <td><%= invoice.comapany %></td>
                <td><%= invoice.contragent %><%= invoice.amount %></td>
                <td><%= invoice.currency %></td>
                <td><%= invoice.data %></td>
                <td><%= link_to 'Show', invoice %></td>
                <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
                <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
      </table>
      </div>

    <div class="panel-footer">

        <%= link_to "New Invoices", new_invoice_path, class: "btn btn-primary" %>
    </div>
</div>
</div>
</div>

app/views/invoices/new.html.erb
<div class="row">
 <div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
   <div class="panel-heading">
   <%= link_to 'Back', invoices_path,class: "btn btn-danger" %>
   
    </div>
        <div class="panel-body"> 
        <%= render 'form' %>
        
      </div>

    </div>
    </div>
    </div>
   

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
 <div class="col-md-8 col-md-offset-2">
  <div class="panel panel-default">
   <div class="panel-heading">
    <h3 class="panel-title">Invoices</h3>
    </div>
        <div class="panel-body">  
            <p>
              <strong>Amount:</strong>
              <%= @invoice.amount %>
            </p>

            <p>
              <strong>Comapany:</strong>
              <%= @invoice.comapany %>
            </p>

            <p>
              <strong>Contragent:</strong>
              <%= @invoice.contragent %>
            </p>

            <p>
              <strong>Currency:</strong>
              <%= @invoice.currency %>
            </p>

            <p>
              <strong>Data:</strong>
              <%= @invoice.data %>
            </p>
<div class="panel-footer">
 <div class="btn-group">
    <%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-danger"  %> |
     <%= link_to 'Back', invoices_path, class: "btn btn-warning" %>
    </div>
  </div>
 </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Invoices</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
	  <nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Invoice</a>
	    </div>
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav">
	    	<li><%= link_to "Invoice", invoices_path %></li>
	    </ul>
     </div>
     </div>
	  </nav>  
	  
	
	<div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>